language: node_js
node_js:
  - "8"

script:
 - npm run build:production
 - npm test

after_success:
 - npm run build-storybook
 - npm run semantic-release

deploy:
  local-dir: "./storybook-static"
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master