language: node_js
node_js:
  - "8"

script:
 - yarn build:production
 - yarn test

after_success:
 - yarn build-storybook

deploy:
  local-dir: "./storybook-static"
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
    
deploy:
  provider: script
  script: yarn semantic-release
  on:
    branch: master